#!/bin/sh
#
# Copyright (C) 2015 Canonical Ltd.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 3, as published
# by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
set -ex

if [ "${1}" = "info" ]; then
    if [ -z "${2}" ]; then
        echo "Usage: click info [options] PATH"
        echo ""
        echo "click: error: need file name"
    fi
    cat `dirname ${0}`/info/${2}
else
    /usr/bin/click ${@}
fi
