#!/bin/sh

set -ex

# Run the integration tests against the installed scope.

export PYTHONPATH=$PYTHONPATH:`pwd`/tests/common
export SCOPE_DIR=/usr/lib/`dpkg-architecture -qDEB_HOST_MULTIARCH`/unity-scopes

(cd tests/scope-harness && xvfb-run -a python3 -m testtools.run discover)
